---
# tasks file for mysql
- name: Installing mysql-server
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Mysql_index
  copy:
    content: "Hi"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: Mysql_index

- name: Start MySQL service
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: Mysql_index.changed
